### PR TITLE
Correction for vulnerability in lodash versions below 4.17.5 #24

### PR DESCRIPTION
**Pull request by smm-telus**

### CODE REVIEW

**Comment by kof** [comment]
Would you like to be added as a maintainer? I am currently not using this package.

**Comment by smm-telus** [comment]
@kof I have another PR coming up to upgrade a few things so that it passes `npm audit`.
When did these 3 tests break? I haven't had a chance to look into the commit history.
```
1) should work with images
2) should work with links
3) should render tags with custom props
```

**Comment by smm-telus** [comment]
..and please @kof add me as a maintainer; don't mind at all.

**Comment by kof** [comment]
seems like only @alexkuz can do it on github, I can on npm

**Pull request merged**
